apiVersion: v1
kind: Pod
metadata:
  name: chainweb
  labels:
    app: chainweb
spec:
  containers:
  - name: chainweb
    image: liqingmubai/chainweb
---
apiVersion: v1
kind: Service
metadata:
  name: chainweb
spec:
  selector:
    app: chainweb
  type: LoadBalancer
  ports:
    - protocol: TCP
      port: 8181
      targetPort: 8181
