settings:
  database:
    name: test
    dbType: mysql
    host: 156.225.2.239
    username: root
    password: BVYRDR2Z7X
    port: 13306
    max-idle-conns: 10
    max-open-conns: 10
    log-mode: false


